### ISSUE TITLE
Cannot start pnpm dev:extension from github clone

### ISSUE THREAD

**Issue by iam-dev** [palladians/pallad#118]
@palladxyz/features:dev: src/common/store/app.ts(3,37): error TS7016: Could not find a declaration file for module '@palladxyz/persistence'. '/Users/.../Documents/pallad/packages/persistence/dist/index.js' implicitly has an 'any' type.
@palladxyz/features:dev:   If the '@palladxyz/persistence' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '@palladxyz/persistence';`
@palladxyz/features:dev: 
@palladxyz/features:dev: [@PALLADXYZ/FEATURES] DTS Build failed
@palladxyz/features:dev: Error: error occured in dts build
@palladxyz/features:dev:     at Worker.<anonymous> (/Users/.../Documents/pallad/node_modules/.pnpm/tsup@8.0.1_postcss@8.4.32_typescript@5.3.3/node_modules/tsup/dist/index.js:2690:26)
@palladxyz/features:dev:     at Worker.emit (node:events:512:28)
@palladxyz/features:dev:     at MessagePort.<anonymous> (node:internal/worker:263:53)
@palladxyz/features:dev:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20)
@palladxyz/features:dev:     at exports.emitMessage (node:internal/per_context/messageport:23:28)
@palladxyz/features:dev: RollupError: Failed to compile. Check the logs above.
@palladxyz/features:dev:     at Object.error (/Users/.../Documents/pallad/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/shared/parseAst.js:279:30)
@palladxyz/features:dev:     at Object.error (/Users/.../Documents/pallad/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/shared/rollup.js:820:32)
@palladxyz/features:dev:     at Object.error (/Users/.../Documents/pallad/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/shared/rollup.js:18635:42)
@palladxyz/features:dev:     at generateDtsFromTs (/Users/.../Documents/pallad/node_modules/.pnpm/tsup@8.0.1_postcss@8.4.32_typescript@5.3.3/node_modules/tsup/dist/rollup.js:7776:22)
@palladxyz/features:dev:     at /Users/.../Documents/pallad/node_modules/.pnpm/tsup@8.0.1_postcss@8.4.32_typescript@5.3.3/node_modules/tsup/dist/rollup.js:7783:59
@palladxyz/features:dev:     at _nullishCoalesce (/Users/.../Documents/pallad/node_modules/.pnpm/tsup@8.0.1_postcss@8.4.32_typescript@5.3.3/node_modules/tsup/dist/rollup.js:1:198)
@palladxyz/features:dev:     at Object.transform (/Users/.../Documents/pallad/node_modules/.pnpm/tsup@8.0.1_postcss@8.4.32_typescript@5.3.3/node_modules/tsup/dist/rollup.js:7783:18)
@palladxyz/features:dev:     at /Users/.../Documents/pallad/node_modules/.pnpm/rollup@4.9.1/node_modules/rollup/dist/shared/rollup.js:1005:40

**Comment by mrcnk** [comment]
Hey @iam-dev, please check now. I've added turbowatch to rerun builds on changed typescript files in the repo.

**Comment by iam-dev** [comment]
works now
