### ISSUE TITLE
zkApp to Wallet Connector Package  🔌 

### ISSUE THREAD

**Issue by teddyjfpender** [palladians/pallad#122]
# zkApp to Wallet Connector Package  🔌 
With Pallad having its own injected provider, it is a good idea to have a client-side version for interacting with Pallad. zkApp developers shouldn't have to spend much time to integrate Pallad for its users to interact with the developer's zkApp. A package that abstracts over the injected provider's functionality could give developers the required quick access to Pallad's features.

It also allows for better testing of Pallad's injected provider in an example zkApp like [Minaverse](https://minaverse.xyz/) 🪐 

# Possible Solutions 💡 
- Wagmi
- Standalone Mina package for all Mina ecosystem wallets

# Requirements 📖 
- Versioning of wallet APIs
- Completion of https://github.com/palladians/pallad/pull/111

**Comment by mrcnk** [comment]
Ongoing work with https://github.com/palladians/mina-js
