### ISSUE TITLE
Add word number label to mnemonic inputs in wallet restoration flow

### ISSUE THREAD

**Issue by mrcnk** [palladians/pallad#190]
## Acceptance Criteria:

- [ ] Each Seed Import input should have a label inside the input with an according word number.
- [ ] It should work fine on smaller side panels - inputs should be responsive.

## Design

![image](https://github.com/user-attachments/assets/7acf763b-2026-42ea-81d6-c66d8d9f6db9)

**Comment by ayseberfinozcubuk** [comment]
@mrcnk Can you assign me?

**Comment by aliraza556** [comment]
@mrcnk Please assign me?

**Comment by mrcnk** [comment]
@all-contributors please add @aliraza556 for code
