### ISSUE TITLE
Fix the date formatting when user hovers Mina price chart

### ISSUE THREAD

**Issue by mrcnk** [palladians/pallad#191]
## Current

Date is formatted with a 3 letters month abbreviation and one digit of a month's day. (Jul 0)

## Expected

Date formatted with a 3 letters month abbreviation and one or two digits of month's day. (Jul 30)

## Screenshot

![image](https://github.com/user-attachments/assets/054dea09-018a-4210-81c3-4ca7d0dbd345)

**Comment by quiqueg** [comment]
@mrcnk I'd be happy to take a look at this. Re: the `bounty` label, are there any details on how to get set up with your bounty program for payout?

**Comment by mrcnk** [comment]
Hey @quiqueg, we'll post more info about the bounty program tomorrow on https://x.com/pallad_. Please check it tomorrow to learn how to get it for implementing it.

**Comment by aliraza556** [comment]
@mrcnk Please assign me this issue?
