### ISSUE TITLE
Add a simple password strength label

### ISSUE THREAD

**Issue by mrcnk** [palladians/pallad#193]
## Acceptance Criteria:

- [ ] The initial screen of both Create Wallet and Restore Wallet has a password strength indicator.
- [ ] It uses zxcvbn or similar library to determine the strength of a password.
- [ ] There should be 3 states of password strength:
  - weak - "Your password is terrible" (#EB6F92 - red)
  - average - Your password could be better" (#F2BEBC - peach)
  - good - "Your password is safe" (#A3DBE4 - mint)

## Design

![image](https://github.com/user-attachments/assets/374ed449-a539-4f45-b111-98b458bb9d20)

**Comment by aliraza556** [comment]
@mrcnk Could you assign me?

**Comment by mrcnk** [comment]
@yaodingyd great job, please open a https://app.astromina.org/ account so I can submit the bounty payout!

**Comment by mrcnk** [comment]
@all-contributors please add @yaodingyd for code
