### ISSUE TITLE
Fix "The spending password is wrong" label in Unlock Wallet route

### ISSUE THREAD

**Issue by mrcnk** [palladians/pallad#197]
## Current

"The spending password is wrong" is displayed on Unlock Wallet route even if user didn't provide a wrong password.

## Expected

The label is only visible after user provided a wrong password.

## Screenshots

![image](https://github.com/user-attachments/assets/0977b4f2-59f7-46b4-8c01-32a55621588c)

**Comment by aliraza556** [comment]
@mrcnk Please assign me?
