### ISSUE TITLE
Portfolio value change calculation is broken when using Mina values

### ISSUE THREAD

**Issue by mrcnk** [palladians/pallad#198]
## Current

When using Mina values on Dashboard, the daily change +0.02 (24h) is broken, displaying pretty much the same value all the time.

## Expected

The value reflects an actual fiat change, but in Mina.

## Screenshots

![image](https://github.com/user-attachments/assets/0f9119e9-4e8c-4e5b-8547-2de7b77d9f44)

**Comment by aliraza556** [comment]
@mrcnk Please assign me?

**Comment by silas315** [comment]
It doesn't work when I use the fiat part. It shows the value as zero
![Uploading palla3.png…]()

**Comment by Tayfun545455** [comment]
good

**Comment by Tayfun545455** [comment]
https://x.com/MisticCrp/status/1827407397045850481

**Comment by gurkan7** [comment]
i will solve this
