### ISSUE TITLE
[Transactions]: Disable `Next` Button When User Attempts to Send Payment to the Same Address

### ISSUE THREAD

**Issue by aliraza556** [palladians/pallad#205]
**Describe the bug**
- The `Next` button is not disabled when a user tries to send a payment to the same address, allowing for potential self-transactions.

### Bug Demo:

https://www.loom.com/share/178e44d8eb454e22ad10a07897cc1ec5

![image](https://github.com/user-attachments/assets/e1ef8c46-5cbf-45a4-b5be-c9b32e0aefb3)

My `Wallet` address:
![image](https://github.com/user-attachments/assets/07771b34-5da6-4d7c-a460-401032d8a352)

### Acceptance Criteria
- [x]  The `Next` button should be automatically disabled if the user enters the same address.

**Comment by aliraza556** [comment]
Hi @mrcnk, could you please review this issue and assign the bounty to me?

**Comment by mrcnk** [comment]
@aliraza556 self transactions in some context are totally fine (rebalancing, memo). There is no bounty for anything that you won't find on https://app.astromina.org/. Closing this one.
