### ISSUE TITLE
Improve dependency situation

### ISSUE THREAD

**Issue by paulmillr** [palladians/pallad#34]
- `bs58check` can be replaced by `@scure/base`
- `pbkdf2`, `get-random-values` can be replaced by `@noble/hashes`
- `lodash` is not used anywhere
- `ethereumjs/util`, I think, already uses noble-hashes and scure-base, so you would get less code in the result bundle

**Comment by teddyjfpender** [comment]
@paulmillr Thank you for your insights and recommendations! I'll dive in and make those improvements! 

We are big fans of your work 🙇

**Comment by paulmillr** [comment]
Thank you!

**Comment by teddyjfpender** [comment]
Resolving this issue in the current `key-management` [PR](https://github.com/palladians/pallad/pull/33#issue-1806130818) 😄
