### ISSUE TITLE
Incorrect Transaction Labels

### ISSUE THREAD

**Issue by teddyjfpender** [palladians/pallad#98]
# Correctly Label Transactions as 'Sent' or 'Received'

All transactions in the wallet are currently labelled as 'Received,' regardless of whether they are incoming or outgoing. This issue needs correction for accurate transaction labelling.

```gherkin
Feature: Accurate labelling of transactions as 'Sent' or 'Received'
  As a user
  I want transactions to be correctly labelled as 'Sent' or 'Received'
  So that I can easily understand my transaction history

  Scenario: Labeling a sent transaction
    Given I have completed a transaction
    When I view the transaction in the transaction history
    Then the transaction should be labelled as 'Sent' or 'Received' based on the transaction type
```

Currently users will see all transactions labelled as 'Received':
![image](https://github.com/palladians/pallad/assets/92999717/dc4c97fb-8a22-4b1c-8045-8c7a68eb2d96)

**Comment by mrcnk** [comment]
Fixed by reporter 😎
